- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: fluentd-config
    namespace: logging
    labels:
      app: fluentd
  data:
    fluent.conf: |
      <source>
        @type tail
        format none
        path /var/log/nginx/access.log
        tag count.format1
      </source>
      <match *.**>
        @type stdout
      </match>