apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: pv-efk
  name: pv-efk
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/efk
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem